package services

// Required columns and types in the last schema before versioned migrations.
var baselineColumns = map[string]map[string]string{
	"folders": {
		"id":                   "bigint",
		"path":                 "text",
		"folder_name":          "text",
		"name":                 "text",
		"url_broken":           "integer",
		"indexed_at":           "timestamp without time zone",
		"share_key":            "text",
		"directory_size_bytes": "bigint",
		"upload_date":          "text",
	},
	"audio_files": {
		"id":                   "bigint",
		"path":                 "text",
		"filename":             "text",
		"indexed_at":           "timestamp without time zone",
		"deleted":              "integer",
		"unavailable_at":       "timestamp with time zone",
		"removal_requested_at": "timestamp with time zone",
		"age_limit":            "integer",
	},
	"play_events": {
		"id":                   "bigint",
		"audio_file_id":        "bigint",
		"played_at":            "timestamp without time zone",
		"session_id":           "text",
		"listening_session_id": "text",
		"origin":               "text",
		"access_key_nonce":     "text",
	},
	"download_events": {
		"id":               "bigint",
		"audio_file_id":    "bigint",
		"downloaded_at":    "timestamp without time zone",
		"event_type":       "text",
		"share_key":        "text",
		"session_id":       "text",
		"client_ip":        "text",
		"user_agent":       "text",
		"referer":          "text",
		"range_header":     "text",
		"method":           "text",
		"file_size":        "bigint",
		"requested_bytes":  "bigint",
		"access_key_nonce": "text",
	},
	"source_requests": {
		"id":            "bigint",
		"submitted_url": "text",
		"title":         "text",
		"status":        "text",
		"tags":          "text",
		"created_at":    "timestamp without time zone",
		"updated_at":    "timestamp without time zone",
		"source_key":    "text",
	},
	"waveform_cache": {
		"id":               "bigint",
		"audio_file_id":    "bigint",
		"peaks":            "text",
		"generated_at":     "timestamp without time zone",
		"duration_seconds": "real",
	},
	"anonymous_profiles": {
		"session_id":        "text",
		"recovery_key_hash": "bytea",
		"created_at":        "timestamp with time zone",
		"updated_at":        "timestamp with time zone",
	},
	"targeted_messages": {
		"id":         "bigint",
		"session_id": "text",
		"title":      "text",
		"message":    "text",
		"created_at": "timestamp with time zone",
	},
	"likes": {
		"profile_id":    "text",
		"audio_file_id": "bigint",
		"created_at":    "timestamp with time zone",
	},
	"playback_access_keys": {
		"access_key_nonce": "text",
		"first_seen_at":    "timestamp with time zone",
		"expires_at":       "timestamp with time zone",
	},
}

var baselineIndexes = []string{
	"idx_folders_parent_path",
	"idx_folders_share_key",
	"idx_audio_files_parent_path",
	"idx_audio_files_downloaded_at",
	"idx_audio_files_source_path",
	"idx_audio_files_share_key",
	"idx_play_events_audio_file_id",
	"idx_play_events_played_at",
	"idx_play_events_session_id",
	"idx_play_events_listening_session_id",
	"idx_play_events_access_key_nonce",
	"idx_playback_access_keys_expires_at",
	"idx_download_events_audio_file_id",
	"idx_download_events_downloaded_at",
	"idx_download_events_event_type",
	"idx_download_events_client_ip",
	"idx_download_events_session_id",
	"idx_download_events_access_key_nonce",
	"idx_source_requests_status",
	"idx_likes_audio_file_id",
	"idx_likes_profile_created_at",
	"idx_targeted_messages_session_id",
	"idx_source_requests_submitted_url",
	"idx_source_requests_source_key",
	"idx_audio_files_unavailable_at",
	"idx_audio_files_removal_requested_at",
	"idx_audio_files_trgm_filename",
	"idx_audio_files_trgm_title",
	"idx_audio_files_trgm_artist",
	"idx_audio_files_trgm_description",
	"idx_folders_trgm_name",
	"idx_folders_trgm_folder_name",
	"idx_audio_files_upload_date",
}
